### ISSUE TITLE
Assigning tasks and setting up kanban board

### ISSUE THREAD

**Issue by bilalrajput09** [bilalrajput09/Javascript-capstone-module2#25]
1. We are a team of **three people**.
2. We have **assigned** all tasks accordingly.

https://github.com/bilalrajput09/Javascript-capstone-module2/projects/2

**Comment by Shisui6** [comment]
Hi @bilalrajput09, @Bellagirl-maker and @AbenezerAssefa 

# Approved 🪄
Your project is complete! Congratulations! 🎉 

## Highlights
- Kanban board setup correctly ✅
- All cards are assigned ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
