### ISSUE TITLE
Peer-to-Peer review

### ISSUE THREAD

**Issue by vanina123** [bilalrajput09/Javascript-capstone-module2#37]
Hi @bilalrajput09 
Greate Job implementing the Kanban Board project using API, also the UI look awesome and very easy to play with. Your group did a great job implementing all the functionalities and testing. 
![BravoGIF](https://user-images.githubusercontent.com/71019051/234791996-bcc9c558-dadf-4aaa-a0cc-d2994ed4e672.gif)

Cheers and happy coding✅✅

**Comment by bilalrajput09** [comment]
Thank you 😊.
